float:
  any:
  - base_args: ['@metric']
    constructor: Alaya
    disabled: false
    docker_tag: ann-benchmarks-alaya
    module: ann_benchmarks.algorithms.alaya
    name: alaya
    run_groups:
      alaya:
        args: [[1]]
        query_args: [[ [30, 15], [40, 20], [60, 30], [80, 40] ]]
        # query_args: [[ [60, 30]]]

