float:
  any:
  - base_args: ['@metric']
    constructor: Alaya
    disabled: false
    docker_tag: ann-benchmarks-alaya
    module: ann_benchmarks.algorithms.alaya
    name: alaya
    run_groups:
      alaya:
        args: [[36]]
        query_args: [[ [60, 30]]]
        # args: [[36, 48, 64]]
        # query_args: [[ [30, 15], [40, 20], [60, 30], [80, 30], [100, 30], [120, 30], [160, 30], [180, 30], [210, 30], [260, 40]]]

